// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Action is what a matched rule does to its tunnel.
 * @readonly
 * @enum {string}
 */
export const Action = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ActionConnect: "connect",
    ActionDisconnect: "disconnect",
};

/**
 * Automation is the per-tunnel condition→action rule model that
 * generalises the older TrustedSSIDs + AutoConnectSSIDs pair (issue #12).
 * Each tunnel owns an ordered list of rules; evaluation decides, from the
 * current network context, whether that tunnel should be connected or
 * disconnected — independently of how it was brought up.
 * 
 * This type is additive: the legacy Rules (TrustedSSIDs / PerTunnel
 * AutoConnectSSIDs) still exist for migration. MigrateFromLegacy builds
 * an equivalent Automation from a legacy Rules value.
 */
export class Automation {
    /**
     * Creates a new Automation instance.
     * @param {Partial<Automation>} [$$source = {}] - The source object to create the Automation.
     */
    constructor($$source = {}) {
        if (!("per_tunnel_rules" in $$source)) {
            /**
             * PerTunnel maps a tunnel name to its ordered rule list.
             * @member
             * @type {{ [_ in string]?: Rule[] }}
             */
            this["per_tunnel_rules"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Automation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Automation}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("per_tunnel_rules" in $$parsedSource) {
            $$parsedSource["per_tunnel_rules"] = $$createField0_0($$parsedSource["per_tunnel_rules"]);
        }
        return new Automation(/** @type {Partial<Automation>} */($$parsedSource));
    }
}

/**
 * Condition is a single match predicate. Only the field relevant to Type
 * is used.
 */
export class Condition {
    /**
     * Creates a new Condition instance.
     * @param {Partial<Condition>} [$$source = {}] - The source object to create the Condition.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ssid"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * CIDR, e.g. "10.0.0.0/24"
             * @member
             * @type {string | undefined}
             */
            this["subnet"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * GatewayMAC fingerprints a SPECIFIC network by its default-gateway
             * (router) MAC address — precise and medium-agnostic, so it
             * disambiguates two different networks that share a common subnet
             * like 192.168.0.0/24. Lower-cased colon form, e.g. "b0:38:6c:...".
             * @member
             * @type {string | undefined}
             */
            this["gateway_mac"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * GatewayIP is the current default gateway's IPv4 address (e.g.
             * "192.168.0.1"). Medium-agnostic like GatewayMAC, but stable across
             * router hardware swaps on the same network.
             * @member
             * @type {string | undefined}
             */
            this["gateway_ip"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * InterfaceName is a physical interface name (e.g. "en0", "Ethernet").
             * Matched case-insensitively against the up, non-tunnel interfaces
             * that currently carry a routable address.
             * @member
             * @type {string | undefined}
             */
            this["interface_name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Start and End bound a local-time window in 24-hour "HH:MM" form.
             * End exclusive; an End before Start wraps past midnight (22:00–06:00
             * is "overnight"). Either may be empty (empty Start = 00:00, empty
             * End = 24:00), so a rule can be day-of-week only.
             * @member
             * @type {string | undefined}
             */
            this["start"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["end"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Days filters the window by weekday, 0=Sunday … 6=Saturday. Empty
             * means every day.
             * @member
             * @type {number[] | undefined}
             */
            this["days"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Label is a human-readable hint shown in the editor for a network
             * condition (e.g. "Office · 192.168.0.0/24"). Not used for matching.
             * @member
             * @type {string | undefined}
             */
            this["label"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Condition instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Condition}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("days" in $$parsedSource) {
            $$parsedSource["days"] = $$createField8_0($$parsedSource["days"]);
        }
        return new Condition(/** @type {Partial<Condition>} */($$parsedSource));
    }
}

/**
 * ConditionDetail reports one condition's match outcome, for the editor's
 * live match indicators. Value is the condition's human-readable target
 * (SSID / CIDR / MAC), empty for wifi and none_match.
 */
export class ConditionDetail {
    /**
     * Creates a new ConditionDetail instance.
     * @param {Partial<ConditionDetail>} [$$source = {}] - The source object to create the ConditionDetail.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("matched" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["matched"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConditionDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConditionDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConditionDetail(/** @type {Partial<ConditionDetail>} */($$parsedSource));
    }
}

/**
 * InterfaceInfo describes one active physical interface. Used by the
 * interface and ethernet conditions.
 */
export class InterfaceInfo {
    /**
     * Creates a new InterfaceInfo instance.
     * @param {Partial<InterfaceInfo>} [$$source = {}] - The source object to create the InterfaceInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("is_wifi" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_wifi"] = false;
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InterfaceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InterfaceInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InterfaceInfo(/** @type {Partial<InterfaceInfo>} */($$parsedSource));
    }
}

/**
 * Rule is one condition→action pair. A rule carries one or more
 * conditions, which are always combined with AND.
 */
export class Rule {
    /**
     * Creates a new Rule instance.
     * @param {Partial<Rule>} [$$source = {}] - The source object to create the Rule.
     */
    constructor($$source = {}) {
        if (!("when" in $$source)) {
            /**
             * When lists the conditions that must hold for the rule to fire.
             * @member
             * @type {Condition[]}
             */
            this["when"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * Match is retained for config compatibility. Conditions are always ANDed;
             * new configs use "all" and legacy configs with no value are equivalent.
             * @member
             * @type {string | undefined}
             */
            this["match"] = undefined;
        }
        if (!("do" in $$source)) {
            /**
             * @member
             * @type {Action}
             */
            this["do"] = Action.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rule instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Rule}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("when" in $$parsedSource) {
            $$parsedSource["when"] = $$createField0_0($$parsedSource["when"]);
        }
        return new Rule(/** @type {Partial<Rule>} */($$parsedSource));
    }
}

/**
 * RuleDetail reports how one rule (and each of its conditions) fared
 * against the current network context. Matched is the overall rule
 * outcome after applying Match (AND/OR).
 */
export class RuleDetail {
    /**
     * Creates a new RuleDetail instance.
     * @param {Partial<RuleDetail>} [$$source = {}] - The source object to create the RuleDetail.
     */
    constructor($$source = {}) {
        if (!("do" in $$source)) {
            /**
             * @member
             * @type {Action}
             */
            this["do"] = Action.$zero;
        }
        if (!("match_all" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["match_all"] = false;
        }
        if (!("matched" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["matched"] = false;
        }
        if (!("conditions" in $$source)) {
            /**
             * @member
             * @type {ConditionDetail[]}
             */
            this["conditions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuleDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuleDetail}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conditions" in $$parsedSource) {
            $$parsedSource["conditions"] = $$createField3_0($$parsedSource["conditions"]);
        }
        return new RuleDetail(/** @type {Partial<RuleDetail>} */($$parsedSource));
    }
}

/**
 * Rules defines WiFi auto-connect behavior. The model is per-tunnel:
 * each tunnel owns the list of SSIDs that should auto-activate it.
 * The "trusted" list is a global override that disconnects auto-managed
 * tunnels when joining those networks.
 */
export class Rules {
    /**
     * Creates a new Rules instance.
     * @param {Partial<Rules>} [$$source = {}] - The source object to create the Rules.
     */
    constructor($$source = {}) {
        if (!("trusted_ssids" in $$source)) {
            /**
             * override: VPN off on these networks
             * @member
             * @type {string[]}
             */
            this["trusted_ssids"] = [];
        }
        if (!("per_tunnel" in $$source)) {
            /**
             * keyed by tunnel name
             * @member
             * @type {{ [_ in string]?: TunnelSSIDs }}
             */
            this["per_tunnel"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rules instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Rules}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType8;
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("trusted_ssids" in $$parsedSource) {
            $$parsedSource["trusted_ssids"] = $$createField0_0($$parsedSource["trusted_ssids"]);
        }
        if ("per_tunnel" in $$parsedSource) {
            $$parsedSource["per_tunnel"] = $$createField1_0($$parsedSource["per_tunnel"]);
        }
        return new Rules(/** @type {Partial<Rules>} */($$parsedSource));
    }
}

/**
 * SSIDPermissionStatus describes whether the process can read the current SSID.
 */
export class SSIDPermissionStatus {
    /**
     * Creates a new SSIDPermissionStatus instance.
     * @param {Partial<SSIDPermissionStatus>} [$$source = {}] - The source object to create the SSIDPermissionStatus.
     */
    constructor($$source = {}) {
        if (!("has_wifi" in $$source)) {
            /**
             * Wi-Fi hardware found
             * @member
             * @type {boolean}
             */
            this["has_wifi"] = false;
        }
        if (!("has_permission" in $$source)) {
            /**
             * SSID access granted (or no WiFi to check)
             * @member
             * @type {boolean}
             */
            this["has_permission"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSIDPermissionStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSIDPermissionStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSIDPermissionStatus(/** @type {Partial<SSIDPermissionStatus>} */($$parsedSource));
    }
}

/**
 * TunnelSSIDs holds the per-tunnel auto-connect list. Wrapped in a
 * struct (rather than just []string) so future per-tunnel fields can
 * be added without changing the JSON shape.
 */
export class TunnelSSIDs {
    /**
     * Creates a new TunnelSSIDs instance.
     * @param {Partial<TunnelSSIDs>} [$$source = {}] - The source object to create the TunnelSSIDs.
     */
    constructor($$source = {}) {
        if (!("auto_connect_ssids" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["auto_connect_ssids"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelSSIDs instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TunnelSSIDs}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("auto_connect_ssids" in $$parsedSource) {
            $$parsedSource["auto_connect_ssids"] = $$createField0_0($$parsedSource["auto_connect_ssids"]);
        }
        return new TunnelSSIDs(/** @type {Partial<TunnelSSIDs>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Rule.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = Condition.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ConditionDetail.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = TunnelSSIDs.createFrom;
const $$createType10 = $Create.Map($Create.Any, $$createType9);
