// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DNSConflict describes one DNS policy conflict between two tunnels.
 */
export class DNSConflict {
    /**
     * Creates a new DNSConflict instance.
     * @param {Partial<DNSConflict>} [$$source = {}] - The source object to create the DNSConflict.
     */
    constructor($$source = {}) {
        if (!("a" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["a"] = "";
        }
        if (!("b" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["b"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["domain"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["other"] = undefined;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {DNSConflictKind}
             */
            this["kind"] = DNSConflictKind.$zero;
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {Severity}
             */
            this["severity"] = Severity.$zero;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSConflict instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DNSConflict}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DNSConflict(/** @type {Partial<DNSConflict>} */($$parsedSource));
    }
}

/**
 * DNSConflictKind enumerates DNS policy conflicts.
 * 
 * DNS routing and IP routing are separate concerns (principle 12): a DNS
 * server address does not decide which tunnel carries the query's traffic —
 * the route table does. So these conflicts live in their own analyzer and
 * are never merged into the route report (principle 28).
 * @readonly
 * @enum {string}
 */
export const DNSConflictKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * DNSConflictDomainOverlap: two tunnels claim the exact same domain.
     * Nothing decides which resolver answers — a true tie.
     */
    DNSConflictDomainOverlap: "domain_overlap",

    /**
     * DNSConflictDomainContained: one claimed domain is a subdomain of
     * another (example.com vs internal.example.com). The more specific
     * entry wins, mirroring longest-prefix match for routes, so this is
     * informational.
     */
    DNSConflictDomainContained: "domain_contained",

    /**
     * DNSConflictDefaultDNS: more than one tunnel is set as the default
     * DNS resolver (principle 29). Only one resolver can be "the"
     * default, so this needs explicit detection.
     */
    DNSConflictDefaultDNS: "default_dns_multiple",

    /**
     * DNSConflictResolvePath: more than one tunnel claims the system's DNS
     * resolve path (principle 33) — "every DNS query must egress through
     * me". Only one CONNECTED tunnel can carry it, so two claims are
     * informational while at most one of them is up (the user may run them
     * at different times) and blocking once both are up.
     */
    DNSConflictResolvePath: "dns_resolve_path_multiple",

    /**
     * DNSConflictResolvePathVsDefault: one tunnel claims the DNS resolve
     * PATH while another claims the system RESOLVER address, so the two
     * disagree about where DNS goes. Blocking as soon as either is up.
     */
    DNSConflictResolvePathVsDefault: "dns_resolve_path_vs_default_dns",
};

/**
 * Family identifies an address family so the analyzers can keep IPv4 and
 * IPv6 comparisons strictly separate.
 * @readonly
 * @enum {string}
 */
export const Family = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    FamilyIPv4: "ipv4",
    FamilyIPv6: "ipv6",
};

/**
 * ProtectionConflict describes one traffic-protection policy conflict.
 */
export class ProtectionConflict {
    /**
     * Creates a new ProtectionConflict instance.
     * @param {Partial<ProtectionConflict>} [$$source = {}] - The source object to create the ProtectionConflict.
     */
    constructor($$source = {}) {
        if (!("a" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["a"] = "";
        }
        if (!("b" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["b"] = "";
        }
        if (!("a_prefix" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["a_prefix"] = "";
        }
        if (!("b_prefix" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["b_prefix"] = "";
        }
        if (!("family" in $$source)) {
            /**
             * @member
             * @type {Family}
             */
            this["family"] = Family.$zero;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {ProtectionConflictKind}
             */
            this["kind"] = ProtectionConflictKind.$zero;
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {Severity}
             */
            this["severity"] = Severity.$zero;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProtectionConflict instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProtectionConflict}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProtectionConflict(/** @type {Partial<ProtectionConflict>} */($$parsedSource));
    }
}

/**
 * ProtectionConflictKind enumerates traffic-protection policy conflicts.
 * 
 * Protection is deliberately analysed separately from routing (principle 27).
 * Two tunnels whose routes are perfectly resolvable by longest-prefix match
 * can still make contradictory protection claims:
 * 
 * 	A: AllowedIPs 10.0.0.0/8,  Traffic Protect = ON
 * 	B: AllowedIPs 10.10.0.0/16, Traffic Protect = ON
 * 
 * Routing is deterministic here (B wins inside 10.10/16), but the policy
 * layer still has two tunnels claiming that 10.10/16 must not leak through
 * any other egress — an unsatisfiable pair of promises if both are up.
 * @readonly
 * @enum {string}
 */
export const ProtectionConflictKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * ProtectionConflictIdentical: two protected tunnels claim the exact
     * same range — the protection promise cannot be kept for both.
     */
    ProtectionConflictIdentical: "protection_identical",

    /**
     * ProtectionConflictNested: one protected range sits inside another
     * protected range. Routable, but the outer tunnel's promise to carry
     * that traffic conflicts with the inner one's.
     */
    ProtectionConflictNested: "protection_nested",
};

/**
 * Report is the complete output of the analyzers for a set of tunnels. Every
 * slice is sorted deterministically so equal input yields byte-identical
 * reports (principle 30).
 */
export class Report {
    /**
     * Creates a new Report instance.
     * @param {Partial<Report>} [$$source = {}] - The source object to create the Report.
     */
    constructor($$source = {}) {
        if (!("routes" in $$source)) {
            /**
             * @member
             * @type {RouteConflict[]}
             */
            this["routes"] = [];
        }
        if (!("dns" in $$source)) {
            /**
             * @member
             * @type {DNSConflict[]}
             */
            this["dns"] = [];
        }
        if (!("protection" in $$source)) {
            /**
             * @member
             * @type {ProtectionConflict[]}
             */
            this["protection"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Report instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Report}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("routes" in $$parsedSource) {
            $$parsedSource["routes"] = $$createField0_0($$parsedSource["routes"]);
        }
        if ("dns" in $$parsedSource) {
            $$parsedSource["dns"] = $$createField1_0($$parsedSource["dns"]);
        }
        if ("protection" in $$parsedSource) {
            $$parsedSource["protection"] = $$createField2_0($$parsedSource["protection"]);
        }
        return new Report(/** @type {Partial<Report>} */($$parsedSource));
    }
}

/**
 * RouteConflict describes one overlapping prefix pair between two tunnels.
 * 
 * Routing and DNS are separate concerns (principle 12) — this struct is
 * about where IP traffic egresses, never about which resolver answers a
 * name. Nothing here rewrites AllowedIPs (principle 26): the analyzer
 * reports, the user decides.
 */
export class RouteConflict {
    /**
     * Creates a new RouteConflict instance.
     * @param {Partial<RouteConflict>} [$$source = {}] - The source object to create the RouteConflict.
     */
    constructor($$source = {}) {
        if (!("a" in $$source)) {
            /**
             * A and B are the two tunnel names, always in deterministic order.
             * @member
             * @type {string}
             */
            this["a"] = "";
        }
        if (!("b" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["b"] = "";
        }
        if (!("a_prefix" in $$source)) {
            /**
             * APrefix / BPrefix are the canonical (masked) prefixes that overlap.
             * @member
             * @type {string}
             */
            this["a_prefix"] = "";
        }
        if (!("b_prefix" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["b_prefix"] = "";
        }
        if (!("family" in $$source)) {
            /**
             * Family is ipv4 or ipv6 — the two are analysed independently
             * (principle 15).
             * @member
             * @type {Family}
             */
            this["family"] = Family.$zero;
        }
        if (!("kind" in $$source)) {
            /**
             * Kind is the geometric relationship of the two prefixes.
             * @member
             * @type {RouteConflictKind}
             */
            this["kind"] = RouteConflictKind.$zero;
        }
        if (!("severity" in $$source)) {
            /**
             * Severity is what the Conflict Policy layer acts on.
             * @member
             * @type {Severity}
             */
            this["severity"] = Severity.$zero;
        }
        if (!("message" in $$source)) {
            /**
             * Message is a short English explanation for logs; the UI localises
             * from Kind instead of showing this verbatim.
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RouteConflict instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RouteConflict}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RouteConflict(/** @type {Partial<RouteConflict>} */($$parsedSource));
    }
}

/**
 * RouteConflictKind enumerates the relationship between two prefixes.
 * @readonly
 * @enum {string}
 */
export const RouteConflictKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * ConflictNone: disjoint ranges. Never reported — listed here so the
     * state machine is explicit (principle 16).
     */
    ConflictNone: "none",

    /**
     * ConflictContained: one prefix strictly contains the other. Under
     * longest-prefix match the more-specific route always wins, so the
     * outcome is deterministic — informational, never blocking
     * (principle 17).
     */
    ConflictContained: "contained",

    /**
     * ConflictIdentical: same prefix in two tunnels. No longest-prefix
     * winner exists — this is the true tie situation (principle 20) and
     * the only routing state that blocks by default.
     */
    ConflictIdentical: "identical",

    /**
     * ConflictPartial: the ranges intersect without either containing the
     * other. Impossible for pure CIDR input but kept so non-CIDR ranges
     * (and future inputs) are classified instead of silently ignored.
     */
    ConflictPartial: "partial",

    /**
     * ConflictFullTunnel: one prefix is 0.0.0.0/0 or ::/0 and covers the
     * other — reported specially as "full tunnel covers this route"
     * (principle 16).
     */
    ConflictFullTunnel: "full_tunnel",
};

/**
 * Severity expresses how strongly a conflict should influence the Conflict
 * Policy layer (principle 22-25). It describes the conflict's determinism,
 * NOT what to do — the caller maps severity to an action.
 * @readonly
 * @enum {string}
 */
export const Severity = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * SeverityInfo: the situation is deterministic and safe — the kernel
     * or resolver picks a winner unambiguously. Surface it for
     * awareness, never block anything.
     */
    SeverityInfo: "info",

    /**
     * SeverityWarning: real ambiguity that the user should know about,
     * but the resulting behaviour is still predictable enough that
     * blocking would be overbearing. Saving is always allowed; manual
     * connect proceeds after a confirmation.
     */
    SeverityWarning: "warning",

    /**
     * SeverityBlocking: a true tie or an unsatisfiable policy — two
     * tunnels claim the same routing/DNS space with no deterministic
     * winner. Manual connect is blocked pending "Connect Anyway";
     * automation refuses to connect and notifies instead of prompting
     * (principle 25).
     */
    SeverityBlocking: "blocking",
};

// Private type creation functions
const $$createType0 = RouteConflict.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = DNSConflict.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ProtectionConflict.createFrom;
const $$createType5 = $Create.Array($$createType4);
