// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AddressConflictPayload is broadcast (EventAddressConflict) when another
 * client already owns one of our tunnel addresses on a different adapter,
 * and is what Tunnel.PendingAddressConflicts returns per unresolved conflict.
 * Software is the inferred owner ("WireGuard (official client)" for a
 * WireGuardTunnel$* service adapter, "unknown" otherwise); Adapter is the
 * conflicting interface name; State is the tunnel's connection state at the
 * moment of detection ("active", "down" or "unknown") so the dialog can
 * describe what is happening right now. Until the user answers the dialog
 * the tunnel's auto-connect stays paused — but the helper never forcibly
 * disconnects or permanently opts the tunnel out: the user's click drives
 * any change.
 */
export class AddressConflictPayload {
    /**
     * Creates a new AddressConflictPayload instance.
     * @param {Partial<AddressConflictPayload>} [$$source = {}] - The source object to create the AddressConflictPayload.
     */
    constructor($$source = {}) {
        if (!("tunnel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tunnel"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("adapter" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["adapter"] = "";
        }
        if (!("software" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["software"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AddressConflictPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AddressConflictPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AddressConflictPayload(/** @type {Partial<AddressConflictPayload>} */($$parsedSource));
    }
}

/**
 * LogEntry is a single structured log record forwarded from the helper
 * to the GUI (and from the GUI to the frontend LogViewer). We keep it flat
 * — no nested attrs — because the viewer just renders a one-line per entry.
 */
export class LogEntry {
    /**
     * Creates a new LogEntry instance.
     * @param {Partial<LogEntry>} [$$source = {}] - The source object to create the LogEntry.
     */
    constructor($$source = {}) {
        if (!("time" in $$source)) {
            /**
             * RFC3339
             * @member
             * @type {string}
             */
            this["time"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * "debug" | "info" | "warn" | "error"
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * "helper" | "gui"
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * one of logging.ValidCategories ("app" when unset)
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * human-readable text (already includes attrs)
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry(/** @type {Partial<LogEntry>} */($$parsedSource));
    }
}

/**
 * SettingsChangedPayload carries a single applied setting so a running
 * GUI can reflect a change made through another client (the CLI). Only
 * the field for the changed setting is non-nil.
 */
export class SettingsChangedPayload {
    /**
     * Creates a new SettingsChangedPayload instance.
     * @param {Partial<SettingsChangedPayload>} [$$source = {}] - The source object to create the SettingsChangedPayload.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["health_check"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["keep_connection_on_idle"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["prevent_system_sleep"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["pin_interface"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["log_level"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ProxyMode / ProxyURL mirror the persisted proxy (used for update
             * checks) so a change applied through another client — the CLI — is
             * reflected live in the Settings UI, the same role the fields above
             * play for the live-apply toggles. They were never part of this
             * payload before, which left the GUI's proxy reflection code dead.
             * @member
             * @type {string | null | undefined}
             */
            this["proxy_mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["proxy_url"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsChangedPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsChangedPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsChangedPayload(/** @type {Partial<SettingsChangedPayload>} */($$parsedSource));
    }
}
