// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConnectionStatus is the single source of truth for tunnel connection state
 * across the whole application. It carries both wire-safe fields (strings,
 * JSON-tagged) that are sent to the frontend, and internal fields (time.Time,
 * `json:"-"`) that the reconnect monitor and other backend services use for
 * duration math.
 * 
 * Note that `LastHandshake` is the *formatted age string* (e.g. "5s", "2m 10s")
 * that the frontend displays, while `LastHandshakeTime` is the absolute
 * timestamp used internally. Wire callers see only the former.
 */
export class ConnectionStatus {
    /**
     * Creates a new ConnectionStatus instance.
     * @param {Partial<ConnectionStatus>} [$$source = {}] - The source object to create the ConnectionStatus.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {State}
             */
            this["state"] = State.$zero;
        }
        if (!("tunnel_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tunnel_name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["interface_name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["duration"] = undefined;
        }
        if (!("rx_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rx_bytes"] = 0;
        }
        if (!("tx_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tx_bytes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_handshake"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * LatencyMs is the most recent measured round-trip time to the
             * endpoint in milliseconds. 0 means "no measurement yet" or "endpoint
             * unreachable" — the frontend treats both the same (renders "—").
             * @member
             * @type {number | undefined}
             */
            this["latency_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error_message"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * LatencyProbeTarget is the address that actually produced LatencyMs
             * (one of the configured candidates), so the UI can show what the
             * number refers to instead of an unattributed figure.
             * @member
             * @type {string | undefined}
             */
            this["latency_probe_target"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * LatencyProbeState reports the outcome of the last probe cycle:
             *   "ok"          — a candidate answered; LatencyMs is its RTT.
             *   "unreachable" — every candidate failed. The tunnel may still be up
             *                   (ICMP is commonly filtered), but from the user's
             *                   point of view nothing behind it answers.
             *   ""            — not measured yet.
             * Distinct from LatencyMs == 0, which is ambiguous between "no
             * measurement" and "nothing reachable".
             * @member
             * @type {string | undefined}
             */
            this["latency_probe_state"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * LatencyProbeResults carries the per-candidate breakdown behind
             * LatencyMs: every candidate is probed every cycle, so the UI can
             * render one row per target with its own health colour instead of a
             * single unattributed number. Empty until the first probe completes.
             * @member
             * @type {ProbeResult[] | undefined}
             */
            this["latency_probe_results"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ActiveTunnels lists the names of all currently connected (or connecting)
             * tunnels. Populated by the multi-tunnel manager so the frontend can show
             * which tunnels are active.
             * 
             * "Active" here means *transitioning or up*: it includes a tunnel that is
             * still connecting and may yet fail. Use EstablishedTunnels for anything
             * that must not lie to the user (green badge, tray icon, tray bubble).
             * @member
             * @type {string[] | undefined}
             */
            this["active_tunnels"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * EstablishedTunnels lists the names of tunnels that have finished
             * setup and reached StateConnected — the subset of ActiveTunnels that
             * genuinely carries traffic. Rendered states (badge, icon, "Connected"
             * popup) key off this list, so a tunnel whose connect attempt fails is
             * never advertised as connected for the duration of its attempt.
             * @member
             * @type {string[] | undefined}
             */
            this["established_tunnels"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Tunnels carries per-tunnel status for multi-tunnel setups. The frontend
             * uses this to show stats for the selected tunnel rather than the "primary".
             * @member
             * @type {ConnectionStatus[] | undefined}
             */
            this["tunnels"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionStatus}
     */
    static createFrom($$source = {}) {
        const $$createField12_0 = $$createType1;
        const $$createField13_0 = $$createType2;
        const $$createField14_0 = $$createType2;
        const $$createField15_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("latency_probe_results" in $$parsedSource) {
            $$parsedSource["latency_probe_results"] = $$createField12_0($$parsedSource["latency_probe_results"]);
        }
        if ("active_tunnels" in $$parsedSource) {
            $$parsedSource["active_tunnels"] = $$createField13_0($$parsedSource["active_tunnels"]);
        }
        if ("established_tunnels" in $$parsedSource) {
            $$parsedSource["established_tunnels"] = $$createField14_0($$parsedSource["established_tunnels"]);
        }
        if ("tunnels" in $$parsedSource) {
            $$parsedSource["tunnels"] = $$createField15_0($$parsedSource["tunnels"]);
        }
        return new ConnectionStatus(/** @type {Partial<ConnectionStatus>} */($$parsedSource));
    }
}

/**
 * InterfaceConfig represents the [Interface] section of a .conf file.
 */
export class InterfaceConfig {
    /**
     * Creates a new InterfaceConfig instance.
     * @param {Partial<InterfaceConfig>} [$$source = {}] - The source object to create the InterfaceConfig.
     */
    constructor($$source = {}) {
        if (!("private_key" in $$source)) {
            /**
             * Required: Base64-encoded 32-byte key
             * @member
             * @type {string}
             */
            this["private_key"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * Required: CIDR addresses (e.g., "10.0.0.2/24")
             * @member
             * @type {string[]}
             */
            this["address"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: DNS servers and/or search domains
             * @member
             * @type {string[] | undefined}
             */
            this["dns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: 0 = auto-detect
             * @member
             * @type {number | undefined}
             */
            this["mtu"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: 0 = random
             * @member
             * @type {number | undefined}
             */
            this["listen_port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: routing table
             * @member
             * @type {string | undefined}
             */
            this["table"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: firewall mark
             * @member
             * @type {string | undefined}
             */
            this["fw_mark"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: script before interface up
             * @member
             * @type {string | undefined}
             */
            this["pre_up"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: script after interface up
             * @member
             * @type {string | undefined}
             */
            this["post_up"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: script before interface down
             * @member
             * @type {string | undefined}
             */
            this["pre_down"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: script after interface down
             * @member
             * @type {string | undefined}
             */
            this["post_down"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Unrecognized keys preserved for round-tripping
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["extra_keys"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * AmneziaWG obfuscation parameters (device-level). These are sent to
             * amneziawg-go via UAPI when Protocol == "amneziawg"; they are ignored
             * (and rejected by the validator) for standard WireGuard configs.
             * H1-H4 accept a single value or a "min-max" range string, matching
             * amneziawg-go's UintRange format.
             * Junk packet count (device-level)
             * @member
             * @type {number | undefined}
             */
            this["jc"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Junk packet min length
             * @member
             * @type {number | undefined}
             */
            this["jmin"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Junk packet max length
             * @member
             * @type {number | undefined}
             */
            this["jmax"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Init packet padding
             * @member
             * @type {number | undefined}
             */
            this["s1"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Response packet padding
             * @member
             * @type {number | undefined}
             */
            this["s2"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Cookie packet padding
             * @member
             * @type {number | undefined}
             */
            this["s3"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Transport packet padding
             * @member
             * @type {number | undefined}
             */
            this["s4"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Init header range
             * @member
             * @type {string | undefined}
             */
            this["h1"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Response header range
             * @member
             * @type {string | undefined}
             */
            this["h2"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Cookie header range
             * @member
             * @type {string | undefined}
             */
            this["h3"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Transport header range
             * @member
             * @type {string | undefined}
             */
            this["h4"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InterfaceConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InterfaceConfig}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        const $$createField11_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("address" in $$parsedSource) {
            $$parsedSource["address"] = $$createField1_0($$parsedSource["address"]);
        }
        if ("dns" in $$parsedSource) {
            $$parsedSource["dns"] = $$createField2_0($$parsedSource["dns"]);
        }
        if ("extra_keys" in $$parsedSource) {
            $$parsedSource["extra_keys"] = $$createField11_0($$parsedSource["extra_keys"]);
        }
        return new InterfaceConfig(/** @type {Partial<InterfaceConfig>} */($$parsedSource));
    }
}

/**
 * PeerConfig represents a [Peer] section of a .conf file.
 */
export class PeerConfig {
    /**
     * Creates a new PeerConfig instance.
     * @param {Partial<PeerConfig>} [$$source = {}] - The source object to create the PeerConfig.
     */
    constructor($$source = {}) {
        if (!("public_key" in $$source)) {
            /**
             * Required: Base64-encoded 32-byte key
             * @member
             * @type {string}
             */
            this["public_key"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional
             * @member
             * @type {string | undefined}
             */
            this["preshared_key"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: host:port
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (!("allowed_ips" in $$source)) {
            /**
             * Required: CIDR list
             * @member
             * @type {string[]}
             */
            this["allowed_ips"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * Optional: seconds (0 = disabled)
             * @member
             * @type {number | undefined}
             */
            this["persistent_keepalive"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Unrecognized keys preserved for round-tripping
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["extra_keys"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PeerConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PeerConfig}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowed_ips" in $$parsedSource) {
            $$parsedSource["allowed_ips"] = $$createField3_0($$parsedSource["allowed_ips"]);
        }
        if ("extra_keys" in $$parsedSource) {
            $$parsedSource["extra_keys"] = $$createField5_0($$parsedSource["extra_keys"]);
        }
        return new PeerConfig(/** @type {Partial<PeerConfig>} */($$parsedSource));
    }
}

/**
 * ProbeResult is the outcome of pinging ONE candidate address.
 * 
 * Every candidate is probed on every cycle — not "first one that answers
 * wins" — because each row answers a different question: the public probes
 * say whether the tunnel path works, the endpoint says whether the peer is
 * reachable, and a user-pinned target says whether that specific host is up.
 * Aggregating them into a single number hid exactly the information that
 * makes the reading useful.
 */
export class ProbeResult {
    /**
     * Creates a new ProbeResult instance.
     * @param {Partial<ProbeResult>} [$$source = {}] - The source object to create the ProbeResult.
     */
    constructor($$source = {}) {
        if (!("target" in $$source)) {
            /**
             * Target is what was pinged, as displayed (may be a hostname).
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * ResolvedIP is Target resolved to an address, when it is not already
             * one. Empty for a literal IP or when resolution failed.
             * @member
             * @type {string | undefined}
             */
            this["resolved_ip"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Kind classifies the row so the UI can label it:
             *   "public"   — a built-in public probe (full tunnels only)
             *   "endpoint" — the peer endpoint
             *   "custom"   — the address the user typed
             * @member
             * @type {string | undefined}
             */
            this["kind"] = undefined;
        }
        if (!("slot" in $$source)) {
            /**
             * Slot is the editor row this probe came from, or -1 for the endpoint
             * (which is not configurable). It lets the UI show a row's live resolved
             * address next to the box the user typed it in — the mapping cannot be
             * done by name, because two slots may hold the same hostname after an
             * edit and the endpoint appears as a target of its own.
             * @member
             * @type {number}
             */
            this["slot"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * Coverage reports whether the probed address actually travels through
             * this tunnel:
             *   "inside"  — inside AllowedIPs (or a full tunnel)
             *   "outside" — outside AllowedIPs on a split tunnel: the probe never
             *               enters the tunnel, so its RTT describes the plain
             *               internet path and the value is meaningless
             *   ""        — not judgeable (unresolvable, or the config is unreadable)
             * Re-evaluated every cycle on purpose: AllowedIPs can be edited and a
             * DDNS name can move to an address outside the tunnel *after* the target
             * was accepted, and a saved-then-invalid target is exactly the case the
             * user asked to be told about.
             * @member
             * @type {string | undefined}
             */
            this["coverage"] = undefined;
        }
        if (!("reachable" in $$source)) {
            /**
             * Reachable reports whether the target answered ICMP.
             * @member
             * @type {boolean}
             */
            this["reachable"] = false;
        }
        if (!("latency_ms" in $$source)) {
            /**
             * LatencyMs is the round-trip time; 0 when unreachable.
             * @member
             * @type {number}
             */
            this["latency_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProbeResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProbeResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProbeResult(/** @type {Partial<ProbeResult>} */($$parsedSource));
    }
}

/**
 * State represents the tunnel connection state.
 * @readonly
 * @enum {string}
 */
export const State = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StateDisconnected: "disconnected",
    StateConnecting: "connecting",
    StateConnected: "connected",
    StateError: "error",
};

/**
 * WireGuardConfig represents a complete WireGuard configuration file.
 */
export class WireGuardConfig {
    /**
     * Creates a new WireGuardConfig instance.
     * @param {Partial<WireGuardConfig>} [$$source = {}] - The source object to create the WireGuardConfig.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * Tunnel name (derived from filename)
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("interface" in $$source)) {
            /**
             * [Interface] section
             * @member
             * @type {InterfaceConfig}
             */
            this["interface"] = (new InterfaceConfig());
        }
        if (!("peers" in $$source)) {
            /**
             * [Peer] sections (1 or more)
             * @member
             * @type {PeerConfig[]}
             */
            this["peers"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * Protocol selects the protocol backend: "" or "wireguard" = standard
             * WireGuard, "amneziawg" = AmneziaWG. It is derived from the config
             * content at parse time (presence of any AWG obfuscation key marks the
             * config as AWG) and is NOT part of the .conf serialization — the same
             * content always re-derives the same protocol.
             * @member
             * @type {string | undefined}
             */
            this["protocol"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * EnableScripts is injected at runtime by the GUI from user settings
             * (Settings → advanced → enable WireGuard scripts). It is NOT part of
             * the on-disk .conf serialization, but it MUST be transmitted over
             * IPC (hence json tag, not `json:"-"`): the helper's reconnect path
             * reuses the cached config and applies the same policy as the
             * initial connect.
             * @member
             * @type {boolean | undefined}
             */
            this["enable_scripts"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * BindIfIndex/BindIfName are injected at runtime by the helper from
             * the tunnel's meta sidecar (per-tunnel physical egress binding, a
             * Settings opt-in feature). They are NOT part of the on-disk .conf
             * serialization. BindIfName is used on Linux (route-level egress
             * pinning); BindIfIndex on Windows (IP_UNICAST_IF socket pinning).
             * @member
             * @type {number | undefined}
             */
            this["bind_if_index"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["bind_if_name"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WireGuardConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WireGuardConfig}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("interface" in $$parsedSource) {
            $$parsedSource["interface"] = $$createField1_0($$parsedSource["interface"]);
        }
        if ("peers" in $$parsedSource) {
            $$parsedSource["peers"] = $$createField2_0($$parsedSource["peers"]);
        }
        return new WireGuardConfig(/** @type {Partial<WireGuardConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ProbeResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = ConnectionStatus.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = InterfaceConfig.createFrom;
const $$createType7 = PeerConfig.createFrom;
const $$createType8 = $Create.Array($$createType7);
