// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as TunnelService from "./tunnelservice.js";
export {
    TunnelService
};

export {
    AutomationPreviewResponse,
    AutomationTunnelPreview,
    ConnectionStatus,
    CurrentNetwork,
    DNSLeakResult,
    DNSServer,
    KnownSSIDs,
    PhysicalInterface,
    PublicDNSRefresh,
    RouteEntry,
    ScriptRef,
    SettingsImportResult,
    TestProxyResult,
    TunnelFields,
    TunnelInfo,
    TunnelMetaBinding,
    TunnelPolicies,
    UpdateState,
    ZipImportResult
} from "./models.js";
