// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wifi$0 from "../wifi/models.js";

/**
 * AutomationPreviewResponse is the GUI-computed read-only evaluation of
 * every tunnel's Automation rules against the current network context. It
 * carries per-rule and per-condition match detail so the editor can render
 * live "this condition matches now" indicators without re-implementing the
 * engine's matching in JS. Computed locally (no helper round-trip) and
 * identical in spirit to the helper's ipc.AutomationPreviewResponse.
 */
export class AutomationPreviewResponse {
    /**
     * Creates a new AutomationPreviewResponse instance.
     * @param {Partial<AutomationPreviewResponse>} [$$source = {}] - The source object to create the AutomationPreviewResponse.
     */
    constructor($$source = {}) {
        if (!("on_wifi" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["on_wifi"] = false;
        }
        if (!("ssid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ssid"] = "";
        }
        if (!("physical_ips" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["physical_ips"] = [];
        }
        if (!("subnets" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["subnets"] = [];
        }
        if (!("gateway_mac" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gateway_mac"] = "";
        }
        if (!("gateway_ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gateway_ip"] = "";
        }
        if (!("interfaces" in $$source)) {
            /**
             * @member
             * @type {wifi$0.InterfaceInfo[]}
             */
            this["interfaces"] = [];
        }
        if (!("tunnels" in $$source)) {
            /**
             * @member
             * @type {AutomationTunnelPreview[]}
             */
            this["tunnels"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutomationPreviewResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AutomationPreviewResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("physical_ips" in $$parsedSource) {
            $$parsedSource["physical_ips"] = $$createField2_0($$parsedSource["physical_ips"]);
        }
        if ("subnets" in $$parsedSource) {
            $$parsedSource["subnets"] = $$createField3_0($$parsedSource["subnets"]);
        }
        if ("interfaces" in $$parsedSource) {
            $$parsedSource["interfaces"] = $$createField6_0($$parsedSource["interfaces"]);
        }
        if ("tunnels" in $$parsedSource) {
            $$parsedSource["tunnels"] = $$createField7_0($$parsedSource["tunnels"]);
        }
        return new AutomationPreviewResponse(/** @type {Partial<AutomationPreviewResponse>} */($$parsedSource));
    }
}

/**
 * AutomationTunnelPreview is one tunnel's evaluated rules plus the overall
 * decision Evaluate would reach (accounting for the manual-off latch).
 */
export class AutomationTunnelPreview {
    /**
     * Creates a new AutomationTunnelPreview instance.
     * @param {Partial<AutomationTunnelPreview>} [$$source = {}] - The source object to create the AutomationTunnelPreview.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("rules" in $$source)) {
            /**
             * @member
             * @type {wifi$0.RuleDetail[]}
             */
            this["rules"] = [];
        }
        if (!("decision" in $$source)) {
            /**
             * "connect" | "disconnect" | "unmanaged" | "manual-off"
             * @member
             * @type {string}
             */
            this["decision"] = "";
        }
        if (!("active" in $$source)) {
            /**
             * tunnel is actually up in the helper
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutomationTunnelPreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AutomationTunnelPreview}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rules" in $$parsedSource) {
            $$parsedSource["rules"] = $$createField1_0($$parsedSource["rules"]);
        }
        return new AutomationTunnelPreview(/** @type {Partial<AutomationTunnelPreview>} */($$parsedSource));
    }
}

/**
 * ConnectionStatus is re-exported from the domain package so Wails bindings
 * expose the same type that the helper broadcasts — preventing field drift
 * between wire format and frontend expectations.
 */
export const ConnectionStatus = domain$0.ConnectionStatus;

/**
 * ConnectionStatus is re-exported from the domain package so Wails bindings
 * expose the same type that the helper broadcasts — preventing field drift
 * between wire format and frontend expectations.
 * @typedef {domain$0.ConnectionStatus} ConnectionStatus
 */

/**
 * CurrentNetwork is the fingerprint of the network the machine is on now,
 * for the Automation editor's "use current network" button.
 */
export class CurrentNetwork {
    /**
     * Creates a new CurrentNetwork instance.
     * @param {Partial<CurrentNetwork>} [$$source = {}] - The source object to create the CurrentNetwork.
     */
    constructor($$source = {}) {
        if (!("gateway_mac" in $$source)) {
            /**
             * "" when unavailable (e.g. Windows, no gateway)
             * @member
             * @type {string}
             */
            this["gateway_mac"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * human hint, e.g. "192.168.0.0/24"
             * @member
             * @type {string}
             */
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CurrentNetwork instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CurrentNetwork}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CurrentNetwork(/** @type {Partial<CurrentNetwork>} */($$parsedSource));
    }
}

/**
 * DNSLeakResult mirrors diag.DNSLeakResult for Wails JSON serialisation.
 */
export class DNSLeakResult {
    /**
     * Creates a new DNSLeakResult instance.
     * @param {Partial<DNSLeakResult>} [$$source = {}] - The source object to create the DNSLeakResult.
     */
    constructor($$source = {}) {
        if (!("leaked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["leaked"] = false;
        }
        if (!("dns_servers" in $$source)) {
            /**
             * @member
             * @type {DNSServer[]}
             */
            this["dns_servers"] = [];
        }
        if (!("test_domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["test_domain"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSLeakResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DNSLeakResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dns_servers" in $$parsedSource) {
            $$parsedSource["dns_servers"] = $$createField1_0($$parsedSource["dns_servers"]);
        }
        return new DNSLeakResult(/** @type {Partial<DNSLeakResult>} */($$parsedSource));
    }
}

/**
 * DNSServer mirrors diag.DNSServer.
 */
export class DNSServer {
    /**
     * Creates a new DNSServer instance.
     * @param {Partial<DNSServer>} [$$source = {}] - The source object to create the DNSServer.
     */
    constructor($$source = {}) {
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("is_vpn" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_vpn"] = false;
        }
        if (!("is_local" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_local"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["source_iface"] = undefined;
        }
        if (!("responds" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["responds"] = false;
        }
        if (!("latency_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["latency_ms"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("encryption" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["encryption"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSServer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DNSServer}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DNSServer(/** @type {Partial<DNSServer>} */($$parsedSource));
    }
}

/**
 * KnownSSIDs is the response shape for GetKnownSSIDs. The frontend uses
 * it to render a picker so users can tap saved networks instead of
 * retyping SSIDs they've already joined.
 */
export class KnownSSIDs {
    /**
     * Creates a new KnownSSIDs instance.
     * @param {Partial<KnownSSIDs>} [$$source = {}] - The source object to create the KnownSSIDs.
     */
    constructor($$source = {}) {
        if (!("current" in $$source)) {
            /**
             * currently-connected SSID (empty if not on Wi-Fi)
             * @member
             * @type {string}
             */
            this["current"] = "";
        }
        if (!("known" in $$source)) {
            /**
             * saved/preferred networks reported by the OS
             * @member
             * @type {string[]}
             */
            this["known"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnownSSIDs instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KnownSSIDs}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("known" in $$parsedSource) {
            $$parsedSource["known"] = $$createField1_0($$parsedSource["known"]);
        }
        return new KnownSSIDs(/** @type {Partial<KnownSSIDs>} */($$parsedSource));
    }
}

/**
 * PhysicalInterface describes one network interface offered in the
 * per-tunnel "physical egress" dropdown (Settings → interface binding).
 * 
 * The naming is deliberately split: `Friendly` is the GENERIC name a human
 * recognises ("以太网" / "WLAN" / "Wi-Fi" / "Ethernet"), while `Hardware`
 * carries the vendor model string ("Realtek PCIe GbE Family Controller").
 * Showing only the hardware name made every entry look alike and gave no
 * clue which port was which.
 */
export class PhysicalInterface {
    /**
     * Creates a new PhysicalInterface instance.
     * @param {Partial<PhysicalInterface>} [$$source = {}] - The source object to create the PhysicalInterface.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * OS interface index (ifIndex)
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * OS device name ("en0", "wlan0", "Ethernet")
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("friendly" in $$source)) {
            /**
             * generic name: "Wi-Fi", "以太网", "Ethernet"
             * @member
             * @type {string}
             */
            this["friendly"] = "";
        }
        if (!("hardware" in $$source)) {
            /**
             * vendor/model detail or device name
             * @member
             * @type {string}
             */
            this["hardware"] = "";
        }
        if (!("is_physical" in $$source)) {
            /**
             * hardware NIC (not tunnel/loopback/virtual)
             * @member
             * @type {boolean}
             */
            this["is_physical"] = false;
        }
        if (!("is_up" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_up"] = false;
        }
        if (!("has_default" in $$source)) {
            /**
             * carries a default route (v4 or v6)
             * @member
             * @type {boolean}
             */
            this["has_default"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PhysicalInterface instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PhysicalInterface}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PhysicalInterface(/** @type {Partial<PhysicalInterface>} */($$parsedSource));
    }
}

/**
 * PublicDNSRefresh is the result of RefreshPublicDNSServers: the list
 * fetched from the live feed, the resolver list now in effect (custom list
 * takes precedence over the fetched one), when the live feed was last
 * fetched (0 = never / failed), and an optional fetch error string.
 */
export class PublicDNSRefresh {
    /**
     * Creates a new PublicDNSRefresh instance.
     * @param {Partial<PublicDNSRefresh>} [$$source = {}] - The source object to create the PublicDNSRefresh.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["fetched"] = undefined;
        }
        if (!("effective" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["effective"] = [];
        }
        if (!("fetched_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fetched_at"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicDNSRefresh instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicDNSRefresh}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fetched" in $$parsedSource) {
            $$parsedSource["fetched"] = $$createField0_0($$parsedSource["fetched"]);
        }
        if ("effective" in $$parsedSource) {
            $$parsedSource["effective"] = $$createField1_0($$parsedSource["effective"]);
        }
        return new PublicDNSRefresh(/** @type {Partial<PublicDNSRefresh>} */($$parsedSource));
    }
}

/**
 * RouteEntry mirrors diag.RouteEntry for Wails JSON serialisation.
 */
export class RouteEntry {
    /**
     * Creates a new RouteEntry instance.
     * @param {Partial<RouteEntry>} [$$source = {}] - The source object to create the RouteEntry.
     */
    constructor($$source = {}) {
        if (!("destination" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["destination"] = "";
        }
        if (!("gateway" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gateway"] = "";
        }
        if (!("interface" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["interface"] = "";
        }
        if (!("flags" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["flags"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["is_vpn"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * InterfaceType is the stable kind label (wifi/ethernet/vpn/…), and
             * InterfaceDetail the creator-app name (Tailscale/Docker/…, not
             * localised) — both produced by diag.classifyIface. The UI renders
             * them as the iface column's "kind · source" badge. They MUST be
             * copied here: this DTO is what actually crosses the IPC boundary,
             * and mirroring diag.RouteEntry field-by-field is easy to forget
             * when a new column is added upstream.
             * @member
             * @type {string | undefined}
             */
            this["interface_type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["interface_detail"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RouteEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RouteEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RouteEntry(/** @type {Partial<RouteEntry>} */($$parsedSource));
    }
}

/**
 * ScriptRef describes whether a hook command references a script file
 * (and where) or is a plain inline shell command.
 */
export class ScriptRef {
    /**
     * Creates a new ScriptRef instance.
     * @param {Partial<ScriptRef>} [$$source = {}] - The source object to create the ScriptRef.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (!("is_file" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_file"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptRef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScriptRef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScriptRef(/** @type {Partial<ScriptRef>} */($$parsedSource));
    }
}

/**
 * SettingsImportResult reports what one import pass produced.
 */
export class SettingsImportResult {
    /**
     * Creates a new SettingsImportResult instance.
     * @param {Partial<SettingsImportResult>} [$$source = {}] - The source object to create the SettingsImportResult.
     */
    constructor($$source = {}) {
        if (!("tunnels" in $$source)) {
            /**
             * @member
             * @type {ZipImportResult[]}
             */
            this["tunnels"] = [];
        }
        if (!("scripts" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["scripts"] = [];
        }
        if (!("settings_applied" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["settings_applied"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsImportResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType10;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tunnels" in $$parsedSource) {
            $$parsedSource["tunnels"] = $$createField0_0($$parsedSource["tunnels"]);
        }
        if ("scripts" in $$parsedSource) {
            $$parsedSource["scripts"] = $$createField1_0($$parsedSource["scripts"]);
        }
        return new SettingsImportResult(/** @type {Partial<SettingsImportResult>} */($$parsedSource));
    }
}

/**
 * TestProxyResult is the outcome of a proxy connectivity test.
 */
export class TestProxyResult {
    /**
     * Creates a new TestProxyResult instance.
     * @param {Partial<TestProxyResult>} [$$source = {}] - The source object to create the TestProxyResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("latency_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["latency_ms"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestProxyResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestProxyResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestProxyResult(/** @type {Partial<TestProxyResult>} */($$parsedSource));
    }
}

/**
 * TunnelFields is the field-editor model for one tunnel config. Values are
 * raw strings; list fields (Address/DNS/AllowedIPs) stay comma-joined. An
 * empty value means "remove this key from the conf".
 */
export class TunnelFields {
    /**
     * Creates a new TunnelFields instance.
     * @param {Partial<TunnelFields>} [$$source = {}] - The source object to create the TunnelFields.
     */
    constructor($$source = {}) {
        if (!("interface" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["interface"] = {};
        }
        if (!("peers" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }[]}
             */
            this["peers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelFields instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TunnelFields}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType11;
        const $$createField1_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("interface" in $$parsedSource) {
            $$parsedSource["interface"] = $$createField0_0($$parsedSource["interface"]);
        }
        if ("peers" in $$parsedSource) {
            $$parsedSource["peers"] = $$createField1_0($$parsedSource["peers"]);
        }
        return new TunnelFields(/** @type {Partial<TunnelFields>} */($$parsedSource));
    }
}

/**
 * TunnelInfo is the summary shown in the tunnel list.
 */
export class TunnelInfo {
    /**
     * Creates a new TunnelInfo instance.
     * @param {Partial<TunnelInfo>} [$$source = {}] - The source object to create the TunnelInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("is_connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_connected"] = false;
        }
        if (!("endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["notes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["latency_probe_target"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Protocol is "" or "wireguard" for standard WireGuard tunnels and
             * "amneziawg" for AmneziaWG tunnels. The frontend shows an AWG badge
             * when it is set, so users can tell at a glance why an AWG tunnel's
             * status path behaves differently (e.g. no `wg` CLI access).
             * @member
             * @type {string | undefined}
             */
            this["protocol"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * CreatedAtUnix is the .conf file's mtime; LastUsedUnix is the most
             * recent connection start from history (0 if never connected). Both
             * feed the tunnel-list "date added" / "last used" sort (issue #17).
             * @member
             * @type {number | undefined}
             */
            this["created_at_unix"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["last_used_unix"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TunnelInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TunnelInfo(/** @type {Partial<TunnelInfo>} */($$parsedSource));
    }
}

/**
 * TunnelMetaBinding is the wire form of the per-tunnel egress binding.
 */
export class TunnelMetaBinding {
    /**
     * Creates a new TunnelMetaBinding instance.
     * @param {Partial<TunnelMetaBinding>} [$$source = {}] - The source object to create the TunnelMetaBinding.
     */
    constructor($$source = {}) {
        if (!("bind_if_index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bind_if_index"] = 0;
        }
        if (!("bind_if_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bind_if_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelMetaBinding instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TunnelMetaBinding}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TunnelMetaBinding(/** @type {Partial<TunnelMetaBinding>} */($$parsedSource));
    }
}

/**
 * TunnelPolicies is the wire form of a tunnel's WireGuide Plus private
 * policies. Like the egress binding, all three live in the .meta.json
 * sidecar and NEVER in the .conf (policy principle 1/2) so the config file
 * stays a portable standard WireGuard/AWG document.
 */
export class TunnelPolicies {
    /**
     * Creates a new TunnelPolicies instance.
     * @param {Partial<TunnelPolicies>} [$$source = {}] - The source object to create the TunnelPolicies.
     */
    constructor($$source = {}) {
        if (!("traffic_protect" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["traffic_protect"] = false;
        }
        if (!("domains" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["domains"] = [];
        }
        if (!("use_as_default_dns" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["use_as_default_dns"] = false;
        }
        if (!("dns_resolve_path" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dns_resolve_path"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelPolicies instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TunnelPolicies}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("domains" in $$parsedSource) {
            $$parsedSource["domains"] = $$createField1_0($$parsedSource["domains"]);
        }
        return new TunnelPolicies(/** @type {Partial<TunnelPolicies>} */($$parsedSource));
    }
}

/**
 * UpdateState is the frontend-facing snapshot of persisted check state.
 * Exposed so Settings → About can render the "Last checked …" line and
 * the first-check placeholder correctly.
 * 
 * IsDevBuild + AutoEnabled together let the UI distinguish three
 * "not-yet-checked" cases that look identical to a naive `last_check==0`
 * gate:
 * 
 * 	dev build  → scheduler is intentionally inert, show "Never checked"
 * 	auto off   → user disabled the scheduler, show "Never checked"
 * 	auto on    → first tick is 30–120 s away, show "scheduled" hint
 * 
 * CurrentVersion is duplicated here (also in GetVersion()) so the About
 * tab doesn't need two round-trips to render.
 */
export class UpdateState {
    /**
     * Creates a new UpdateState instance.
     * @param {Partial<UpdateState>} [$$source = {}] - The source object to create the UpdateState.
     */
    constructor($$source = {}) {
        if (!("current_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current_version"] = "";
        }
        if (!("last_check_unix" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["last_check_unix"] = 0;
        }
        if (!("last_seen_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_seen_version"] = "";
        }
        if (!("dismissed_versions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["dismissed_versions"] = [];
        }
        if (!("is_dev_build" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_dev_build"] = false;
        }
        if (!("auto_enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateState}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dismissed_versions" in $$parsedSource) {
            $$parsedSource["dismissed_versions"] = $$createField3_0($$parsedSource["dismissed_versions"]);
        }
        return new UpdateState(/** @type {Partial<UpdateState>} */($$parsedSource));
    }
}

/**
 * ZipImportResult holds the outcome of importing one .conf entry from a zip.
 */
export class ZipImportResult {
    /**
     * Creates a new ZipImportResult instance.
     * @param {Partial<ZipImportResult>} [$$source = {}] - The source object to create the ZipImportResult.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ZipImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ZipImportResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ZipImportResult(/** @type {Partial<ZipImportResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = wifi$0.InterfaceInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = AutomationTunnelPreview.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = wifi$0.RuleDetail.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = DNSServer.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = ZipImportResult.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Map($Create.Any, $Create.Any);
const $$createType12 = $Create.Array($$createType11);
