// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wifi$0 from "../wifi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Session is one VPN session record. EndTime is a pointer so a still-active
 * session (no end yet) can be distinguished from a completed session that
 * happens to have ended at time.Time{} — the previous flat-struct design
 * couldn't tell those apart and showed phantom "0s" rows in the UI when the
 * helper was killed mid-connect before the disconnect path could write
 * final stats.
 */
export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tunnel_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tunnel_name"] = "";
        }
        if (!("start_time" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["start_time"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["end_time"] = undefined;
        }
        if (!("duration_sec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_sec"] = 0;
        }
        if (!("rx_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rx_bytes"] = 0;
        }
        if (!("tx_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tx_bytes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["disconnect_reason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}

/**
 * Settings holds application-wide settings.
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("language" in $$source)) {
            /**
             * "auto", "en", "ko", "ja", "zh"
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("theme" in $$source)) {
            /**
             * "dark", "light", "system"
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("tray_icon_style" in $$source)) {
            /**
             * "color" (MVP: color only)
             * @member
             * @type {string}
             */
            this["tray_icon_style"] = "";
        }
        if (!("auto_start" in $$source)) {
            /**
             * launch GUI on OS login
             * @member
             * @type {boolean}
             */
            this["auto_start"] = false;
        }
        if (!("start_minimized" in $$source)) {
            /**
             * start hidden in the tray
             * @member
             * @type {boolean}
             */
            this["start_minimized"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * NotifyDurationMs is how long the connection-status notification
             * bubble stays on screen (ms). 0 means the default (10s).
             * @member
             * @type {number | undefined}
             */
            this["notify_duration_ms"] = undefined;
        }
        if (!("kill_switch" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["kill_switch"] = false;
        }
        if (!("dns_protection" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dns_protection"] = false;
        }
        if (!("health_check" in $$source)) {
            /**
             * periodic handshake age monitoring
             * @member
             * @type {boolean}
             */
            this["health_check"] = false;
        }
        if (!("pin_interface" in $$source)) {
            /**
             * pin bypass routes to upstream interface (-ifscope)
             * @member
             * @type {boolean}
             */
            this["pin_interface"] = false;
        }
        if (!("log_level" in $$source)) {
            /**
             * "debug", "info", "warn", "error"
             * @member
             * @type {string}
             */
            this["log_level"] = "";
        }
        if (!("compact_list" in $$source)) {
            /**
             * dense tunnel list: hide endpoint line, shorter rows
             * @member
             * @type {boolean}
             */
            this["compact_list"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * LogRetentionDays is how many days of daily log files to keep.
             * 0 means the default (7). Files older than this are removed at
             * startup and whenever settings are saved.
             * @member
             * @type {number | undefined}
             */
            this["log_retention_days"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * HistoryRetentionDays is how many days of connection history to keep.
             * 0 means the default (7). Records older than this are pruned whenever
             * the history is loaded for display.
             * @member
             * @type {number | undefined}
             */
            this["history_retention_days"] = undefined;
        }
        if (!("enable_wg_scripts" in $$source)) {
            /**
             * EnableWgScripts controls whether PreUp/PostUp/PreDown/PostDown
             * scripts embedded in tunnel configs are executed. OFF by default:
             * scripts run inside the privileged helper (root/admin) and arbitrary
             * config-driven commands are a security risk. Enabling shows a
             * prominent warning in Settings.
             * @member
             * @type {boolean}
             */
            this["enable_wg_scripts"] = false;
        }
        if (!("list_sort" in $$source)) {
            /**
             * ListSort controls tunnel-list ordering: "name_asc" (default),
             * "name_desc". ListActiveOnTop floats connected tunnels above the
             * sort. Both are pure view state managed from the list header.
             * @member
             * @type {string}
             */
            this["list_sort"] = "";
        }
        if (!("list_active_on_top" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["list_active_on_top"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * ListPaneWidth is the draggable width (px) of the tunnel-list
             * column. 0 falls back to the default.
             * @member
             * @type {number | undefined}
             */
            this["list_pane_width"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * AutoUpdateCheck controls the periodic update scheduler. *bool so we
             * can distinguish "user never touched this" from "user explicitly
             * turned it off" — defaults to true on first load. A user who installs
             * via brew might prefer to disable in-app checks and let brew handle
             * it instead; an offline / corporate-network user might disable to
             * silence the failed-check log noise.
             * @member
             * @type {boolean | null | undefined}
             */
            this["auto_update_check"] = undefined;
        }
        if (!("wifi_rules" in $$source)) {
            /**
             * WifiRules holds the LEGACY SSID-based auto-connect / auto-disconnect
             * policy. Retained for migration; superseded by Automation. Once
             * Automation is populated it is the source of truth and WifiRules is
             * no longer consulted by the rule engine.
             * @member
             * @type {wifi$0.Rules}
             */
            this["wifi_rules"] = (new wifi$0.Rules());
        }
        if (/** @type {any} */(false)) {
            /**
             * Automation is the per-tunnel condition→action rule model (issue
             * #12). A nil pointer means "not yet migrated from WifiRules";
             * EnsureAutomation() populates it once from the legacy rules. A
             * non-nil (possibly empty) value means the user is on the new model.
             * @member
             * @type {wifi$0.Automation | null | undefined}
             */
            this["automation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ManualOffTunnels lists tunnels the user has manually switched off
             * from the UI or tray menu. While a tunnel is listed, the automation
             * engine refuses to auto-connect it even when rules match — the user's
             * manual off wins until they manually reconnect that tunnel once or
             * the app restarts (the GUI clears the list on startup).
             * @member
             * @type {string[] | undefined}
             */
            this["manual_off_tunnels"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ProxyMode controls outbound proxying for update checks: "direct"
             * (default, no proxy), "mirror" (rewrite the API URL through a GitHub
             * accelerator prefix stored in ProxyURL) or "manual" (use ProxyURL as
             * an HTTP/SOCKS proxy). Intended for users who can't reach GitHub
             * directly (e.g. mainland China) — they can route update checks through
             * an accelerator mirror or a local HTTP/SOCKS proxy.
             * @member
             * @type {string | undefined}
             */
            this["proxy_mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ProxyURL is the proxy address used when ProxyMode is "manual" (e.g.
             * "http://127.0.0.1:7890" or "socks5://127.0.0.1:1080"), or the
             * accelerator prefix used when ProxyMode is "mirror" (e.g.
             * "https://ghfast.top").
             * @member
             * @type {string | undefined}
             */
            this["proxy_url"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField19_0 = $$createType0;
        const $$createField20_0 = $$createType2;
        const $$createField21_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("wifi_rules" in $$parsedSource) {
            $$parsedSource["wifi_rules"] = $$createField19_0($$parsedSource["wifi_rules"]);
        }
        if ("automation" in $$parsedSource) {
            $$parsedSource["automation"] = $$createField20_0($$parsedSource["automation"]);
        }
        if ("manual_off_tunnels" in $$parsedSource) {
            $$parsedSource["manual_off_tunnels"] = $$createField21_0($$parsedSource["manual_off_tunnels"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = wifi$0.Rules.createFrom;
const $$createType1 = wifi$0.Automation.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($Create.Any);
