// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wifi$0 from "../wifi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * LegacyDataItem describes one file that exists in the legacy directory and
 * can be copied to the current location.
 */
export class LegacyDataItem {
    /**
     * Creates a new LegacyDataItem instance.
     * @param {Partial<LegacyDataItem>} [$$source = {}] - The source object to create the LegacyDataItem.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {LegacyDataKind}
             */
            this["kind"] = LegacyDataKind.$zero;
        }
        if (!("name" in $$source)) {
            /**
             * display name, e.g. "config.json", "tunnels/office.conf", "logs/wireguide.log"
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("source_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_path"] = "";
        }
        if (!("target_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target_path"] = "";
        }
        if (!("target_exists" in $$source)) {
            /**
             * a file with the same name already exists at the target
             * @member
             * @type {boolean}
             */
            this["target_exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LegacyDataItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LegacyDataItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LegacyDataItem(/** @type {Partial<LegacyDataItem>} */($$parsedSource));
    }
}

/**
 * LegacyDataKind classifies a migratable file so the UI can group and label
 * items.
 * @readonly
 * @enum {string}
 */
export const LegacyDataKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * config.json, history.json
     */
    LegacyConfigFile: "config",

    /**
     * tunnels/*.conf
     */
    LegacyTunnelFile: "tunnel",

    /**
     * legacy logs dir files
     */
    LegacyLogFile: "log",
};

/**
 * LegacyDataReport is the result of a legacy-data scan. Found is true when at
 * least one migratable item exists. Migrated/Dismissed reflect the persisted
 * migration state so the GUI can avoid nagging a user who already decided.
 */
export class LegacyDataReport {
    /**
     * Creates a new LegacyDataReport instance.
     * @param {Partial<LegacyDataReport>} [$$source = {}] - The source object to create the LegacyDataReport.
     */
    constructor($$source = {}) {
        if (!("found" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["found"] = false;
        }
        if (!("legacy_config_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["legacy_config_dir"] = "";
        }
        if (!("legacy_logs_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["legacy_logs_dir"] = "";
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {LegacyDataItem[]}
             */
            this["items"] = [];
        }
        if (!("config_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["config_count"] = 0;
        }
        if (!("tunnel_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tunnel_count"] = 0;
        }
        if (!("log_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["log_count"] = 0;
        }
        if (!("conflict_count" in $$source)) {
            /**
             * items whose target already exists
             * @member
             * @type {number}
             */
            this["conflict_count"] = 0;
        }
        if (!("migrated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["migrated"] = false;
        }
        if (!("dismissed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dismissed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LegacyDataReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LegacyDataReport}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField3_0($$parsedSource["items"]);
        }
        return new LegacyDataReport(/** @type {Partial<LegacyDataReport>} */($$parsedSource));
    }
}

/**
 * MigrateOptions controls a migration run.
 */
export class MigrateOptions {
    /**
     * Creates a new MigrateOptions instance.
     * @param {Partial<MigrateOptions>} [$$source = {}] - The source object to create the MigrateOptions.
     */
    constructor($$source = {}) {
        if (!("overwrite" in $$source)) {
            /**
             * Overwrite replaces target files that already exist. Without it,
             * conflicting items are skipped (reported in MigrateResult.Skipped).
             * @member
             * @type {boolean}
             */
            this["overwrite"] = false;
        }
        if (!("include_logs" in $$source)) {
            /**
             * IncludeLogs migrates the legacy logs directory. Off by default:
             * logs are recreatable and often useless after an upgrade.
             * @member
             * @type {boolean}
             */
            this["include_logs"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigrateOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MigrateOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MigrateOptions(/** @type {Partial<MigrateOptions>} */($$parsedSource));
    }
}

/**
 * MigrateResult reports per-file outcomes by display name.
 */
export class MigrateResult {
    /**
     * Creates a new MigrateResult instance.
     * @param {Partial<MigrateResult>} [$$source = {}] - The source object to create the MigrateResult.
     */
    constructor($$source = {}) {
        if (!("migrated" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["migrated"] = [];
        }
        if (!("skipped" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["skipped"] = [];
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["failed"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigrateResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MigrateResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("migrated" in $$parsedSource) {
            $$parsedSource["migrated"] = $$createField0_0($$parsedSource["migrated"]);
        }
        if ("skipped" in $$parsedSource) {
            $$parsedSource["skipped"] = $$createField1_0($$parsedSource["skipped"]);
        }
        if ("failed" in $$parsedSource) {
            $$parsedSource["failed"] = $$createField2_0($$parsedSource["failed"]);
        }
        return new MigrateResult(/** @type {Partial<MigrateResult>} */($$parsedSource));
    }
}

/**
 * Session is one VPN session record. EndTime is a pointer so a still-active
 * session (no end yet) can be distinguished from a completed session that
 * happens to have ended at time.Time{} — the previous flat-struct design
 * couldn't tell those apart and showed phantom "0s" rows in the UI when the
 * helper was killed mid-connect before the disconnect path could write
 * final stats.
 */
export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tunnel_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tunnel_name"] = "";
        }
        if (!("start_time" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["start_time"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["end_time"] = undefined;
        }
        if (!("duration_sec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_sec"] = 0;
        }
        if (!("rx_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rx_bytes"] = 0;
        }
        if (!("tx_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tx_bytes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["disconnect_reason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}

/**
 * Settings holds application-wide settings.
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("language" in $$source)) {
            /**
             * "auto", "en", "ko", "ja", "zh"
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("theme" in $$source)) {
            /**
             * "dark", "light", "system"
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("tray_icon_style" in $$source)) {
            /**
             * "color" (MVP: color only)
             * @member
             * @type {string}
             */
            this["tray_icon_style"] = "";
        }
        if (!("auto_start" in $$source)) {
            /**
             * launch GUI on OS login
             * @member
             * @type {boolean}
             */
            this["auto_start"] = false;
        }
        if (!("start_minimized" in $$source)) {
            /**
             * start hidden in the tray
             * @member
             * @type {boolean}
             */
            this["start_minimized"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * NotifyDurationMs is how long the connection-status notification
             * bubble stays on screen (ms). 0 means the default (10s).
             * @member
             * @type {number | undefined}
             */
            this["notify_duration_ms"] = undefined;
        }
        if (!("kill_switch" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["kill_switch"] = false;
        }
        if (!("dns_protection" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dns_protection"] = false;
        }
        if (!("health_check" in $$source)) {
            /**
             * periodic handshake age monitoring
             * @member
             * @type {boolean}
             */
            this["health_check"] = false;
        }
        if (!("pin_interface" in $$source)) {
            /**
             * pin bypass routes to upstream interface (-ifscope)
             * @member
             * @type {boolean}
             */
            this["pin_interface"] = false;
        }
        if (!("log_level" in $$source)) {
            /**
             * "debug", "info", "warn", "error"
             * @member
             * @type {string}
             */
            this["log_level"] = "";
        }
        if (!("compact_list" in $$source)) {
            /**
             * dense tunnel list: hide endpoint line, shorter rows
             * @member
             * @type {boolean}
             */
            this["compact_list"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * LogRetentionDays is how many days of daily log files to keep.
             * 0 means the default (7). Files older than this are removed at
             * startup and whenever settings are saved.
             * @member
             * @type {number | undefined}
             */
            this["log_retention_days"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * HistoryRetentionDays is how many days of connection history to keep.
             * 0 means the default (7). Records older than this are pruned whenever
             * the history is loaded for display.
             * @member
             * @type {number | undefined}
             */
            this["history_retention_days"] = undefined;
        }
        if (!("enable_wg_scripts" in $$source)) {
            /**
             * EnableWgScripts controls whether PreUp/PostUp/PreDown/PostDown
             * scripts embedded in tunnel configs are executed. OFF by default:
             * scripts run inside the privileged helper (root/admin) and arbitrary
             * config-driven commands are a security risk. Enabling shows a
             * prominent warning in Settings.
             * @member
             * @type {boolean}
             */
            this["enable_wg_scripts"] = false;
        }
        if (!("enable_awg" in $$source)) {
            /**
             * EnableAWG controls whether AmneziaWG (AWG) tunnel configs are allowed
             * to connect. ON by default. It is an escape hatch: AWG runs on a fork
             * of WireGuard (amneziawg-go) with obfuscation, and if that backend
             * misbehaves on a given machine the user can disable it and get a clear
             * "AmneziaWG is disabled" error instead of a broken connect. Disabling
             * does NOT downgrade AWG configs to plain WireGuard — the server side
             * requires the obfuscated handshake, so AWG tunnels simply refuse to
             * connect until this is re-enabled.
             * @member
             * @type {boolean}
             */
            this["enable_awg"] = false;
        }
        if (!("list_sort" in $$source)) {
            /**
             * ListSort controls tunnel-list ordering: "name_asc" (default),
             * "name_desc". ListActiveOnTop floats connected tunnels above the
             * sort. Both are pure view state managed from the list header.
             * @member
             * @type {string}
             */
            this["list_sort"] = "";
        }
        if (!("list_active_on_top" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["list_active_on_top"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * ListPaneWidth is the draggable width (px) of the tunnel-list
             * column. 0 falls back to the default.
             * @member
             * @type {number | undefined}
             */
            this["list_pane_width"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * AutoUpdateCheck controls the periodic update scheduler. *bool so we
             * can distinguish "user never touched this" from "user explicitly
             * turned it off" — defaults to true on first load. A user who installs
             * via brew might prefer to disable in-app checks and let brew handle
             * it instead; an offline / corporate-network user might disable to
             * silence the failed-check log noise.
             * @member
             * @type {boolean | null | undefined}
             */
            this["auto_update_check"] = undefined;
        }
        if (!("wifi_rules" in $$source)) {
            /**
             * WifiRules holds the LEGACY SSID-based auto-connect / auto-disconnect
             * policy. Retained for migration; superseded by Automation. Once
             * Automation is populated it is the source of truth and WifiRules is
             * no longer consulted by the rule engine.
             * @member
             * @type {wifi$0.Rules}
             */
            this["wifi_rules"] = (new wifi$0.Rules());
        }
        if (/** @type {any} */(false)) {
            /**
             * Automation is the per-tunnel condition→action rule model (issue
             * #12). A nil pointer means "not yet migrated from WifiRules";
             * EnsureAutomation() populates it once from the legacy rules. A
             * non-nil (possibly empty) value means the user is on the new model.
             * @member
             * @type {wifi$0.Automation | null | undefined}
             */
            this["automation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ManualOffTunnels lists tunnels the user has manually switched off
             * from the UI or tray menu. While a tunnel is listed, the automation
             * engine refuses to auto-connect it even when rules match — the user's
             * manual off wins until they manually reconnect that tunnel once or
             * the app restarts (the GUI clears the list on startup).
             * @member
             * @type {string[] | undefined}
             */
            this["manual_off_tunnels"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ProxyMode controls outbound proxying for update checks: "direct"
             * (default, no proxy), "mirror" (rewrite the API URL through a GitHub
             * accelerator prefix stored in ProxyURL) or "manual" (use ProxyURL as
             * an HTTP/SOCKS proxy). Intended for users who can't reach GitHub
             * directly (e.g. mainland China) — they can route update checks through
             * an accelerator mirror or a local HTTP/SOCKS proxy.
             * @member
             * @type {string | undefined}
             */
            this["proxy_mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ProxyURL is the proxy address used when ProxyMode is "manual" (e.g.
             * "http://127.0.0.1:7890" or "socks5://127.0.0.1:1080"), or the
             * accelerator prefix used when ProxyMode is "mirror" (e.g.
             * "https://ghfast.top").
             * @member
             * @type {string | undefined}
             */
            this["proxy_url"] = undefined;
        }
        if (!("dns_test_public_servers" in $$source)) {
            /**
             * DNSTestPublicServers is the user's customized list of public DNS
             * resolvers probed as a cross-check by the DNS leak test. nil or empty
             * means "no customization" — the effective list falls back to the
             * network-fetched list (DNSTestPublicFetched) when available, else the
             * built-in defaults. A non-empty list replaces the defaults verbatim.
             * Clearing the list NEVER disables public probing: public cross-check is
             * core to the leak test, so an empty custom list simply restores the
             * default cross-check set. The DNS leak panel edits this list.
             * @member
             * @type {string[]}
             */
            this["dns_test_public_servers"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * DNSTestPublicFetched caches the last network-fetched public DNS list
             * (see diag.FetchPublicResolvers) so the effective default cross-check
             * set stays current even offline / when a later refresh fails. It is
             * overridden by DNSTestPublicServers when the user customizes.
             * @member
             * @type {string[] | undefined}
             */
            this["dns_test_public_fetched"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * DNSTestPublicFetchedAt is the unix timestamp of the last successful
             * network fetch of DNSTestPublicFetched (0 = never fetched).
             * @member
             * @type {number | undefined}
             */
            this["dns_test_public_fetched_at"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField20_0 = $$createType3;
        const $$createField21_0 = $$createType5;
        const $$createField22_0 = $$createType2;
        const $$createField25_0 = $$createType2;
        const $$createField26_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("wifi_rules" in $$parsedSource) {
            $$parsedSource["wifi_rules"] = $$createField20_0($$parsedSource["wifi_rules"]);
        }
        if ("automation" in $$parsedSource) {
            $$parsedSource["automation"] = $$createField21_0($$parsedSource["automation"]);
        }
        if ("manual_off_tunnels" in $$parsedSource) {
            $$parsedSource["manual_off_tunnels"] = $$createField22_0($$parsedSource["manual_off_tunnels"]);
        }
        if ("dns_test_public_servers" in $$parsedSource) {
            $$parsedSource["dns_test_public_servers"] = $$createField25_0($$parsedSource["dns_test_public_servers"]);
        }
        if ("dns_test_public_fetched" in $$parsedSource) {
            $$parsedSource["dns_test_public_fetched"] = $$createField26_0($$parsedSource["dns_test_public_fetched"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = LegacyDataItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = wifi$0.Rules.createFrom;
const $$createType4 = wifi$0.Automation.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
